// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EFCoreMovies.CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        partial void Initialize()
        {
            var cinemaHallMovie = CinemaHallMovieEntityType.Create(this);
            var actor = ActorEntityType.Create(this);
            var address = AddressEntityType.Create(this);
            var address0 = Address0EntityType.Create(this);
            var cinema = CinemaEntityType.Create(this);
            var address1 = Address1EntityType.Create(this);
            var cinemaDetail = CinemaDetailEntityType.Create(this);
            var cinemaHall = CinemaHallEntityType.Create(this);
            var cinemaOffer = CinemaOfferEntityType.Create(this);
            var genre = GenreEntityType.Create(this);
            var cinemaWithoutLocation = CinemaWithoutLocationEntityType.Create(this);
            var movieWithCounts = MovieWithCountsEntityType.Create(this);
            var log = LogEntityType.Create(this);
            var message = MessageEntityType.Create(this);
            var movie = MovieEntityType.Create(this);
            var movieActor = MovieActorEntityType.Create(this);
            var payment = PaymentEntityType.Create(this);
            var person = PersonEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var genreMovie = GenreMovieEntityType.Create(this);
            var cardPayment = CardPaymentEntityType.Create(this, payment);
            var merchandising = MerchandisingEntityType.Create(this, product);
            var paypalPayment = PaypalPaymentEntityType.Create(this, payment);
            var rentableMovie = RentableMovieEntityType.Create(this, product);

            CinemaHallMovieEntityType.CreateForeignKey1(cinemaHallMovie, cinemaHall);
            CinemaHallMovieEntityType.CreateForeignKey2(cinemaHallMovie, movie);
            AddressEntityType.CreateForeignKey1(address, actor);
            Address0EntityType.CreateForeignKey1(address0, actor);
            Address1EntityType.CreateForeignKey1(address1, cinema);
            CinemaDetailEntityType.CreateForeignKey1(cinemaDetail, cinema);
            CinemaHallEntityType.CreateForeignKey1(cinemaHall, cinema);
            CinemaOfferEntityType.CreateForeignKey1(cinemaOffer, cinema);
            MessageEntityType.CreateForeignKey1(message, person);
            MessageEntityType.CreateForeignKey2(message, person);
            MovieActorEntityType.CreateForeignKey1(movieActor, actor);
            MovieActorEntityType.CreateForeignKey2(movieActor, movie);
            GenreMovieEntityType.CreateForeignKey1(genreMovie, genre);
            GenreMovieEntityType.CreateForeignKey2(genreMovie, movie);
            MerchandisingEntityType.CreateForeignKey1(merchandising, product);
            RentableMovieEntityType.CreateForeignKey1(rentableMovie, product);

            CinemaHallEntityType.CreateSkipNavigation1(cinemaHall, movie, cinemaHallMovie);
            GenreEntityType.CreateSkipNavigation1(genre, movie, genreMovie);
            MovieEntityType.CreateSkipNavigation1(movie, cinemaHall, cinemaHallMovie);
            MovieEntityType.CreateSkipNavigation2(movie, genre, genreMovie);

            CinemaHallMovieEntityType.CreateAnnotations(cinemaHallMovie);
            ActorEntityType.CreateAnnotations(actor);
            AddressEntityType.CreateAnnotations(address);
            Address0EntityType.CreateAnnotations(address0);
            CinemaEntityType.CreateAnnotations(cinema);
            Address1EntityType.CreateAnnotations(address1);
            CinemaDetailEntityType.CreateAnnotations(cinemaDetail);
            CinemaHallEntityType.CreateAnnotations(cinemaHall);
            CinemaOfferEntityType.CreateAnnotations(cinemaOffer);
            GenreEntityType.CreateAnnotations(genre);
            CinemaWithoutLocationEntityType.CreateAnnotations(cinemaWithoutLocation);
            MovieWithCountsEntityType.CreateAnnotations(movieWithCounts);
            LogEntityType.CreateAnnotations(log);
            MessageEntityType.CreateAnnotations(message);
            MovieEntityType.CreateAnnotations(movie);
            MovieActorEntityType.CreateAnnotations(movieActor);
            PaymentEntityType.CreateAnnotations(payment);
            PersonEntityType.CreateAnnotations(person);
            ProductEntityType.CreateAnnotations(product);
            GenreMovieEntityType.CreateAnnotations(genreMovie);
            CardPaymentEntityType.CreateAnnotations(cardPayment);
            MerchandisingEntityType.CreateAnnotations(merchandising);
            PaypalPaymentEntityType.CreateAnnotations(paypalPayment);
            RentableMovieEntityType.CreateAnnotations(rentableMovie);

            AddAnnotation("ProductVersion", "6.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
